-- INSERT INTO clientes (id, nombre, apellido, email, created_at) VALUES(1, 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
-- INSERT INTO clientes (id, nombre, apellido, email, created_at) VALUES(2, 'John', 'Doe', 'john.doe@gmail.com', '2017-08-28');
-- INSERT INTO clientes (id, nombre, apellido, email, created_at) VALUES(3, 'John', 'wick', 'john.wick@gmail.com', '2020-08-28');